import 'package:demo_app/models/alimento.dart';

class AlimentoService {
  List<Alimento> obtenerAlimentos() {
    return [
      Alimento(
        id: 1,
        nombre: 'Taco al Pastor',
        descripcion: 'Tortilla de maíz con pastor',
        precio: 20,
        foto: 'assets/img/taco_pastor.jpg',
        idCategoria: 1,
        ranking: 5,
      ),
      Alimento(
        id: 2,
        nombre: 'Taco de Suadero',
        descripcion: 'Suadero tradicional',
        precio: 14,
        foto: 'assets/img/taco_res.jpg',
        idCategoria: 1,
        ranking: 4,
      ),
      Alimento(
        id: 3,
        nombre: 'Torta Suadero',
        descripcion: 'Torta especial',
        precio: 60,
        foto: 'assets/img/torta_suadero.jpg',
        idCategoria: 2,
        ranking: 5,
      ),
      Alimento(
        id: 4,
        nombre: 'Torta Pastor',
        descripcion: 'Torta especial',
        precio: 60,
        foto: 'assets/img/torta_pastor.jpg',
        idCategoria: 2,
        ranking: 5,
      ),
      Alimento(
        id: 5,
        nombre: 'Torta de Bistec',
        descripcion: 'Torta de carne de res, verdura y quesillo',
        precio: 80,
        foto: 'assets/img/torta_bistec.jpg',
        idCategoria: 2,
        ranking: 5,
      ),
      Alimento(
        id: 6,
        nombre: 'Torta Campechana',
        descripcion: '2 carne a elegir, verdura y quesillo',
        precio: 80,
        foto: 'assets/img/torta_campechana.jpg',
        idCategoria: 2,
        ranking: 5,
      ),
      Alimento(
        id: 7,
        nombre: 'Taco de Tripa',
        descripcion: 'Carne de viceras de res',
        precio: 18,
        foto: 'assets/img/taco_tripa.jpg',
        idCategoria: 1,
        ranking: 4,
      ),
      Alimento(
        id: 8,
        nombre: 'Taco de Longaniza',
        descripcion: 'Carne de cerdo marinada',
        precio: 14,
        foto: 'assets/img/taco_longaniza.jpg',
        idCategoria: 1,
        ranking: 4,
      ),
      Alimento(
        id: 9,
        nombre: 'Taco Campechano',
        descripcion: 'Carne de Res y Cerdo',
        precio: 14,
        foto: 'assets/img/taco_res.jpg',
        idCategoria: 1,
        ranking: 4,
      ),
      Alimento(
        id: 10,
        nombre: 'Taco de Arrachera',
        descripcion: 'Carne de res jugosa proveniente del diafragma',
        precio: 30,
        foto: 'assets/img/taco_arrachera.jpg',
        idCategoria: 3,
        ranking: 4,
      ),
      Alimento(
        id: 11,
        nombre: 'Burrito al Pastor',
        descripcion: 'Tortilla de arina, queso y carne de cerdo',
        precio: 120,
        foto: 'assets/img/burrito_pastor.jpg',
        idCategoria: 3,
        ranking: 4,
      ),
      Alimento(
        id: 12,
        nombre: 'Burrito de Suadero',
        descripcion: 'Tortilla de arina, queso y carne de res',
        precio: 120,
        foto: 'assets/img/burrito_suadero.jpg',
        idCategoria: 3,
        ranking: 4,
      ),
      Alimento(
        id: 13,
        nombre: 'Burrito al Campechano',
        descripcion: 'Tortilla de arina, queso y carne de cerdo',
        precio: 120,
        foto: 'assets/img/burrito_campechano.jpg',
        idCategoria: 3,
        ranking: 4,
      ),
      Alimento(
        id: 14,
        nombre: 'Volcan de Pastor',
        descripcion: 'Carne de cerdo y queso en tortilla de maiz dorada',
        precio: 160,
        foto: 'assets/img/volcan_pastor.jpg',
        idCategoria: 3,
        ranking: 4,
      ),
      Alimento(
        id: 15,
        nombre: 'Volcan de Suadero',
        descripcion: 'Carne de res y queso en tortilla de maiz dorada',
        precio: 80,
        foto: 'assets/img/volcan_suadero.jpg',
        idCategoria: 3,
        ranking: 4,
      ),
      Alimento(
        id: 16,
        nombre: 'Alambre de Suadero',
        descripcion: 'Carne de res, pimiento, cebolla y quesillo',
        precio: 120,
        foto: 'assets/img/alambre_suadero.jpg',
        idCategoria: 4,
        ranking: 4,
      ),
      Alimento(
        id: 17,
        nombre: 'Alambre de Pastor',
        descripcion: 'Carne de cerdo, pimiento, cebolla y quesillo',
        precio: 120,
        foto: 'assets/img/alambre_pastor.jpg',
        idCategoria: 4,
        ranking: 4,
      ),
      Alimento(
        id: 18,
        nombre: 'Alambre de Arrachera',
        descripcion: 'Carne de res, pimiento, cebolla y quesillo',
        precio: 120,
        foto: 'assets/img/alambre_arrachera.jpg',
        idCategoria: 4,
        ranking: 4,
      ),
      Alimento(
        id: 19,
        nombre: 'Alambre de Bistec',
        descripcion: 'Carne de res, pimiento, cebolla y quesillo',
        precio: 120,
        foto: 'assets/img/alambre_bistec.jpg',
        idCategoria: 4,
        ranking: 4,
      ),
      Alimento(
        id: 20,
        nombre: 'Alambre Campechano',
        descripcion: '2 carnes a elegir, pimiento, cebolla y quesillo',
        precio: 140,
        foto: 'assets/img/alambre_campechano.jpg',
        idCategoria: 4,
        ranking: 4,
      ),
    ];
  }
}
